version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.2
    dns_search:
      - elasticsearch
    ports:
      - 9200:9200

  kibana:
    build:
      context: ./environment/
      dockerfile: Dockerfile.kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  php:
    image: php:7.0-cli
    volumes:
      - ".:/examples:ro"
    depends_on:
      - elasticsearch
    entrypoint: php
    command: "-h"
    working_dir: /examples
